# Read in example json
example_json_file <- system.file("inputs/national_community_child_health_database_(ncchd)_20240405T130125.json", package = "browseMetadata")
dataset <- jsonlite::fromJSON(example_json_file)$dataModel

test_that("json_table_to_df gives expected output for 8th index", {
  result <- json_table_to_df(dataset, 8)

  expected <- data.frame(
    label = c("SECTOR", "PROV_UNIT_CD", "CLIENT_ID_E", "TEST_DT", "TEST_RESULT_CD", "TEST_CD", "AVAIL_FROM_DT", "TDATE_EST"),
    description = c(
      "_",
      "Provider unit code - the NHS trust organisation code for the provider / Local Health Board.",
      "Unique encrypted client identifier - generated by CCH2000 for child in the trust. Needs to be used along with PROV_UNIT_CD to uniquely identify a child.",
      "Date if blood test.",
      "Code indicating outcome of blood test. NOTE - codes are different starting pre/post 2012. Pre-2012 codes range from A-M, and Post-2012 codes range from 01-10.",
      "Type of blood test.",
      "Date when the data made available i.e. date of loading",
      "_"
    ),
    type = c("CHARACTER", "CHARACTER", "BIGINT", "TIMESTAMP", "CHARACTER", "CHARACTER", "DATE", "CHARACTER")
  )

  expected_ordered <- expected[order(expected$label), ]

  expect_equal(result, expected_ordered)
})
